name: Submodule Update Template
on:
  workflow_call:
    inputs:
      submodule_path:
        description: 'Path to submodule directory'
        required: true
        type: string
      submodule_name:
        description: 'Name of submodule'
        required: true
        type: string
      repo_url:
        description: 'Git URL of submodule repository'
        required: true
        type: string

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Commit and push submodule changes
        run: |
          cd ${{ inputs.submodule_path }}
          git add .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Update ${{ inputs.submodule_name }} from dpd-db" || echo "No changes to commit"
          git push origin main
